### ISSUE TITLE
Not able to install?

### ISSUE THREAD

**Issue by mittalyashu** [robrich/gulp-ignore#10]
I don't know, what problem it is. But I am not able to install your plugin.

**Comment by robrich** [comment]
Odd.  What's the error message you see?

**Comment by mittalyashu** [comment]
It shows this message in command prompt.

![image](https://user-images.githubusercontent.com/29014463/32101869-8e7efa1c-bb37-11e7-9c1c-f2a06b5c870d.png)

But the problem is that it doesn't add any package in the node_modules folder not it adds any details package.json file.

**Comment by robrich** [comment]
That's weird. Try `npm cache clean` then try installing again.

**Comment by robrich** [comment]
The other thing to note here is it's failing to install `gulp` dependencies, so as soon as you can successfully run `npm install gulp` then this should work without issue.

**Comment by mittalyashu** [comment]
I have tried re-installing gulp also.

**Comment by robrich** [comment]
Did Gulp install correctly after `npm cache clean`?

**Comment by mittalyashu** [comment]
Yup.

**Comment by robrich** [comment]
Weird. Let me restate to make sure I understand fully. You can install gulp
just fine, but can't install gulp-igore. You're using gulp 3.9.1 (latest),
and gulp-ignore 2.0.2 (latest). Do I understand this correctly?

What version of npm and node are you using? I'm using node 8.8.0 and npm
5.5.1 and it installs just fine for me.

**Comment by mittalyashu** [comment]
Yes. I am able to install the gulp, but not able to install the gulp-ignore (packages).
![image](https://user-images.githubusercontent.com/29014463/32237001-c7be6a60-be89-11e7-8953-69b519c50640.png)

I have tried to install many other packages and they install perfectly.

**Comment by robrich** [comment]
Can you install `gulp-match`?  That's the only dependency that `gulp-ignore` has that `gulp` doesn't.

Are you behind a firewall or proxy?  What version of Node and NPM are you using?

**Comment by mittalyashu** [comment]
What is `gulp-match`?

Are you behind a firewall or proxy? Nope

What version of Node and NPM are you using?
![image](https://user-images.githubusercontent.com/29014463/32404023-f99f068e-c16d-11e7-8fca-c0493fbfb7a7.png)

**Comment by robrich** [comment]
gulp-match is the library that compares vinyl filenames to minimatch patterns.  In theory, if gulp-match installs but gulp-ignore doesn't, we've learned something.  I have to say though this is a head scratcher as usually `npm cache clean` gets us past this.

**Comment by mittalyashu** [comment]
I tried to install and it works. thanks
