### ISSUE TITLE
Gulp ignore, not ignoring.

### ISSUE THREAD

**Issue by CrashyBang** [robrich/gulp-ignore#6]
In my [Gulpfile](https://github.com/Beardedweb/Gulp-Bootstrap-Sass-Template/blob/master/Gulpfile.js) I have the following Task:

    // HTML
    gulp.task('html', function() {
      return  gulp.src(path.join(config.src, '/**/*.html'))
        .pipe(ignore.exclude(config.include))
        .pipe(fileinclude())
        .pipe(connect.reload())
        .pipe(gulp.dest(config.dist))
    });

I am using [gulp-ignore][1] to exclude the `includes` directory however it is not working and includes all ways ends up in the ``dist`` folder.

I assume I have set the variable right:

    var config = {
       include: 'src/includes' // Includes Directory
    };

so this is the line I am having trouble with:

    .pipe(ignore.exclude(config.include))

Anyone come across something similar?

Full [Gulpfile](https://github.com/Beardedweb/Gulp-Bootstrap-Sass-Template/blob/master/Gulpfile.js).

  [1]: https://www.npmjs.com/package/gulp-ignore

**Comment by mouryaamit** [comment]
@robrich Nothing working.
@CrashyBang did you got any solution.

**Comment by Jakobud** [comment]
It's not working at all for me either. I'm not sure what I could be doing wrong. It seems like it should be very straightforward.

**Comment by markfarrall** [comment]
I can now see the key point in the documentation, but it took a while to sink in. You need to use the vinyl-fs object for your conditions.

So for file name comparison you need to use the path item of the vinyl-fs object. Taking the example from the last comment something like this should work:

```
return gulp.src('./public/**/*')
	.pipe(gulpIgnore.exclude(function(file) {		
		if (file.path.indexOf('public/favicon.ico') > 0)
			return true;
	}))
	.pipe(gulp.dest('./build'));
```

**Comment by stevematdavies** [comment]
Not working here, nothing being excluded

**Comment by robrich** [comment]
Stephen,

Do you have an example gulpfile on GitHub or pastebin that shows this
behavior?

**Comment by stevematdavies** [comment]
Not any longer, I went with another solution

**Comment by emilsoman** [comment]
@stevematdavies what solution did you go with ?

**Comment by emilsoman** [comment]
As the README says, you can pass in anything that works with `gulp-match`, so it should work if you pass in something like this : `.pipe(gulpIgnore.exclude(/public\/favicon\.ico/))`

**Comment by juhamust** [comment]
Same issue here. End up using `gulp-filter`: https://www.npmjs.com/package/gulp-filter (which also required few tries and errors, though)

**Comment by robrich** [comment]
Globs are pretty finiky.  @CrashyBang: change your exclude glob to `'src/includes/**'` or `'src/includes/**/*.html'` to ensure it matches.  As you wrote it, the glob believes `inclues` is a file, not a folder.  Want to PR to improve the glob docs?
