### ISSUE TITLE
Better file matching?

### ISSUE THREAD

**Issue by ryepdx** [robrich/gulp-ignore#8]
I would expect any one of the globs `/home/dev/devenv/dappsys/src/sol/token/old_asset/*`, `/home/dev/devenv/dappsys/src/sol/token/old_asset/*.*`, and `/home/dev/devenv/dappsys/src/sol/token/old_asset/*.sol` to match the path `/home/dev/devenv/dappsys/src/sol/token/old_asset/asset0.sol`, but it appears that none of them presently do.

**Edit:** I'm assuming this is a bug, not a feature. Please correct me if I'm wrong here.

**Comment by robrich** [comment]
What is your base directory?

**Comment by ryepdx** [comment]
Ah, okay. That appears to have been the piece I was missing. I'd been operating under the impression it matched files based on `file.path`. Subtracting `file.base` from my globs fixed it.
